"""
Seed script — completa os controlos ISO/IEC 27001:2022 Annex A (93 controlos).

Categorias usadas (PT):
- 5.x → 'Organizacional'
- 6.x → 'Pessoas'
- 7.x → 'Físico'
- 8.x → 'Tecnológico'

Usa INSERT OR IGNORE: preserva os controlos já existentes (com status/owner reais)
e adiciona apenas os que faltam, com defaults conservadores (not_implemented / untested).
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
import sqlite3

DB = os.path.join(os.path.dirname(__file__), "risksafe.db")

# (id, code, name, description, category, framework_refs, status, effectiveness, owner, risk_ids, notes)
ISO_CONTROLS = [
    # ─── 5. Organizational controls ──────────────────────────────────────────
    ("A.5.1",  "A.5.1",  "Políticas para segurança de informação",
     "A política de segurança de informação e políticas específicas por tópico devem ser definidas, aprovadas pela direção, publicadas, comunicadas e reconhecidas pelo pessoal relevante e partes interessadas, e revistas em intervalos planeados ou quando ocorram alterações significativas.",
     "Organizacional", "ISO 27001:2022 A.5.1", "implemented", "effective", "ISO", "", ""),
    ("A.5.2",  "A.5.2",  "Papéis e responsabilidades de segurança de informação",
     "Os papéis e responsabilidades de segurança de informação devem ser definidos e atribuídos de acordo com as necessidades da organização.",
     "Organizacional", "ISO 27001:2022 A.5.2", "implemented", "effective", "ISO", "", ""),
    ("A.5.3",  "A.5.3",  "Segregação de funções",
     "Funções conflituantes e áreas de responsabilidade conflituantes devem ser segregadas.",
     "Organizacional", "ISO 27001:2022 A.5.3", "partial", "needs_improvement", "ISO / RH", "", ""),
    ("A.5.4",  "A.5.4",  "Responsabilidades da direção",
     "A direção deve exigir a todo o pessoal que aplique segurança de informação de acordo com a política, políticas específicas e procedimentos estabelecidos pela organização.",
     "Organizacional", "ISO 27001:2022 A.5.4", "implemented", "effective", "Direção", "", ""),
    ("A.5.5",  "A.5.5",  "Contacto com autoridades",
     "A organização deve estabelecer e manter contacto com as autoridades relevantes.",
     "Organizacional", "ISO 27001:2022 A.5.5", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.6",  "A.5.6",  "Contacto com grupos de interesse especial",
     "A organização deve estabelecer e manter contacto com grupos de interesse especial ou outros fóruns especializados em segurança e associações profissionais.",
     "Organizacional", "ISO 27001:2022 A.5.6", "planned", "untested", "ISO", "", ""),
    ("A.5.7",  "A.5.7",  "Inteligência sobre ameaças",
     "Informação relativa a ameaças à segurança de informação deve ser recolhida e analisada para produzir inteligência sobre ameaças (Threat Intelligence).",
     "Organizacional", "ISO 27001:2022 A.5.7", "not_implemented", "untested", "DTI - Segurança", "", ""),
    ("A.5.8",  "A.5.8",  "Segurança de informação na gestão de projetos",
     "A segurança de informação deve ser integrada na gestão de projetos.",
     "Organizacional", "ISO 27001:2022 A.5.8", "partial", "needs_improvement", "PMO / ISO", "", ""),
    ("A.5.9",  "A.5.9",  "Inventário de informação e ativos associados",
     "Um inventário de informação e outros ativos associados, incluindo proprietários, deve ser desenvolvido e mantido.",
     "Organizacional", "ISO 27001:2022 A.5.9", "partial", "needs_improvement", "DTI", "", ""),
    ("A.5.10", "A.5.10", "Uso aceitável de informação e outros ativos",
     "Regras para o uso aceitável e procedimentos para o tratamento de informação e outros ativos devem ser identificados, documentados e implementados.",
     "Organizacional", "ISO 27001:2022 A.5.10", "implemented", "effective", "ISO", "", ""),
    ("A.5.11", "A.5.11", "Devolução de ativos",
     "Pessoal e outras partes interessadas, conforme aplicável, devem devolver todos os ativos da organização na sua posse após mudança ou cessação do contrato.",
     "Organizacional", "ISO 27001:2022 A.5.11", "implemented", "effective", "RH", "", ""),
    ("A.5.12", "A.5.12", "Classificação de informação",
     "A informação deve ser classificada de acordo com as necessidades de segurança da organização baseadas em confidencialidade, integridade, disponibilidade e requisitos relevantes das partes interessadas.",
     "Organizacional", "ISO 27001:2022 A.5.12", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.13", "A.5.13", "Rotulagem de informação",
     "Um conjunto adequado de procedimentos para rotulagem de informação deve ser desenvolvido e implementado de acordo com o esquema de classificação adotado.",
     "Organizacional", "ISO 27001:2022 A.5.13", "not_implemented", "untested", "ISO", "", ""),
    ("A.5.14", "A.5.14", "Transferência de informação",
     "Regras, procedimentos ou acordos de transferência de informação devem estar em vigor para todos os tipos de transferência dentro da organização e entre a organização e outras partes.",
     "Organizacional", "ISO 27001:2022 A.5.14", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.15", "A.5.15", "Controlo de acessos",
     "Regras para controlar o acesso físico e lógico a informação e outros ativos devem ser estabelecidas e implementadas com base em requisitos de negócio e de segurança de informação.",
     "Organizacional", "ISO 27001:2022 A.5.15", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.5.16", "A.5.16", "Gestão de identidades",
     "O ciclo de vida completo das identidades deve ser gerido.",
     "Organizacional", "ISO 27001:2022 A.5.16", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.5.17", "A.5.17", "Informação de autenticação",
     "A alocação e gestão da informação de autenticação deve ser controlada por um processo de gestão, incluindo aconselhar o pessoal sobre o manuseamento adequado.",
     "Organizacional", "ISO 27001:2022 A.5.17", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.5.18", "A.5.18", "Direitos de acesso",
     "Os direitos de acesso a informação e outros ativos devem ser provisionados, revistos, modificados e removidos de acordo com a política e regras de controlo de acessos.",
     "Organizacional", "ISO 27001:2022 A.5.18", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.5.19", "A.5.19", "Segurança da informação em relações com fornecedores",
     "Processos e procedimentos devem ser definidos e implementados para gerir os riscos de segurança de informação associados ao uso de produtos ou serviços de fornecedores.",
     "Organizacional", "ISO 27001:2022 A.5.19", "planned", "untested", "Compras / ISO", "", ""),
    ("A.5.20", "A.5.20", "Tratamento de segurança de informação em acordos com fornecedores",
     "Requisitos relevantes de segurança de informação devem ser estabelecidos e acordados com cada fornecedor, com base no tipo de relação de fornecimento.",
     "Organizacional", "ISO 27001:2022 A.5.20", "planned", "untested", "Compras / ISO", "", ""),
    ("A.5.21", "A.5.21", "Gestão de segurança de informação na cadeia de fornecimento TIC",
     "Processos e procedimentos devem ser definidos e implementados para gerir os riscos de segurança de informação associados à cadeia de abastecimento de produtos e serviços TIC.",
     "Organizacional", "ISO 27001:2022 A.5.21", "not_implemented", "untested", "Compras / ISO", "", ""),
    ("A.5.22", "A.5.22", "Monitorização, revisão e gestão de mudança de serviços de fornecedores",
     "A organização deve monitorizar, rever, avaliar e gerir a mudança nas práticas de segurança de informação dos fornecedores e na entrega dos serviços.",
     "Organizacional", "ISO 27001:2022 A.5.22", "not_implemented", "untested", "Compras / ISO", "", ""),
    ("A.5.23", "A.5.23", "Segurança de informação no uso de serviços de nuvem",
     "Processos para aquisição, uso, gestão e saída de serviços de nuvem devem ser estabelecidos de acordo com os requisitos de segurança de informação da organização.",
     "Organizacional", "ISO 27001:2022 A.5.23", "partial", "needs_improvement", "DTI / ISO", "", ""),
    ("A.5.24", "A.5.24", "Planeamento e preparação para gestão de incidentes",
     "A organização deve planear e preparar a gestão de incidentes de segurança de informação definindo, estabelecendo e comunicando processos, papéis e responsabilidades.",
     "Organizacional", "ISO 27001:2022 A.5.24", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.25", "A.5.25", "Avaliação e decisão sobre eventos de segurança",
     "A organização deve avaliar eventos de segurança de informação e decidir se devem ser categorizados como incidentes.",
     "Organizacional", "ISO 27001:2022 A.5.25", "partial", "needs_improvement", "ISO / SOC", "", ""),
    ("A.5.26", "A.5.26", "Resposta a incidentes de segurança",
     "Incidentes de segurança de informação devem ser respondidos de acordo com os procedimentos documentados.",
     "Organizacional", "ISO 27001:2022 A.5.26", "partial", "needs_improvement", "ISO / SOC", "", ""),
    ("A.5.27", "A.5.27", "Aprendizagem a partir de incidentes",
     "O conhecimento adquirido com incidentes de segurança de informação deve ser usado para fortalecer e melhorar os controlos.",
     "Organizacional", "ISO 27001:2022 A.5.27", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.28", "A.5.28", "Recolha de evidências",
     "A organização deve estabelecer e implementar procedimentos para identificação, recolha, aquisição e preservação de evidências relacionadas com eventos de segurança.",
     "Organizacional", "ISO 27001:2022 A.5.28", "not_implemented", "untested", "ISO / Forense", "", ""),
    ("A.5.29", "A.5.29", "Segurança da informação durante disrupção",
     "A organização deve planear como manter a segurança de informação a um nível apropriado durante uma disrupção.",
     "Organizacional", "ISO 27001:2022 A.5.29", "not_implemented", "ineffective", "ISO / BCP", "", ""),
    ("A.5.30", "A.5.30", "Prontidão TIC para continuidade de negócio",
     "A prontidão TIC deve ser planeada, implementada, mantida e testada com base nos objetivos de continuidade de negócio e nos requisitos de continuidade TIC.",
     "Organizacional", "ISO 27001:2022 A.5.30", "partial", "needs_improvement", "DTI", "", ""),
    ("A.5.31", "A.5.31", "Requisitos legais, estatutários, regulamentares e contratuais",
     "Requisitos legais, estatutários, regulamentares e contratuais relevantes para a segurança de informação devem ser identificados, documentados e mantidos atualizados.",
     "Organizacional", "ISO 27001:2022 A.5.31", "implemented", "effective", "Jurídico / ISO", "", ""),
    ("A.5.32", "A.5.32", "Direitos de propriedade intelectual",
     "A organização deve implementar procedimentos apropriados para proteger direitos de propriedade intelectual.",
     "Organizacional", "ISO 27001:2022 A.5.32", "partial", "needs_improvement", "Jurídico", "", ""),
    ("A.5.33", "A.5.33", "Proteção de registos",
     "Os registos devem ser protegidos contra perda, destruição, falsificação, acesso não autorizado e divulgação não autorizada.",
     "Organizacional", "ISO 27001:2022 A.5.33", "partial", "needs_improvement", "ISO", "", ""),
    ("A.5.34", "A.5.34", "Privacidade e proteção de informação pessoal (PII)",
     "A organização deve identificar e cumprir os requisitos relativos à preservação da privacidade e proteção de PII de acordo com leis aplicáveis e requisitos contratuais.",
     "Organizacional", "ISO 27001:2022 A.5.34 · RGPD", "partial", "needs_improvement", "DPO", "", ""),
    ("A.5.35", "A.5.35", "Revisão independente da segurança de informação",
     "A abordagem da organização para gerir a segurança de informação e a sua implementação deve ser revista independentemente em intervalos planeados ou quando ocorram alterações significativas.",
     "Organizacional", "ISO 27001:2022 A.5.35", "not_implemented", "untested", "Auditoria Interna", "", ""),
    ("A.5.36", "A.5.36", "Conformidade com políticas, regras e padrões",
     "A conformidade com a política de segurança de informação, políticas específicas, regras e normas da organização deve ser regularmente revista.",
     "Organizacional", "ISO 27001:2022 A.5.36", "partial", "needs_improvement", "ISO / Auditoria", "", ""),
    ("A.5.37", "A.5.37", "Procedimentos operacionais documentados",
     "Procedimentos operacionais para instalações de processamento de informação devem ser documentados e disponibilizados ao pessoal que deles necessite.",
     "Organizacional", "ISO 27001:2022 A.5.37", "partial", "needs_improvement", "DTI", "", ""),

    # ─── 6. People controls ──────────────────────────────────────────────────
    ("A.6.1", "A.6.1", "Triagem",
     "Verificações de antecedentes em todos os candidatos a pessoal devem ser realizadas antes de ingresso na organização e numa base contínua, considerando leis, regulamentos, ética, requisitos de negócio, classificação da informação e riscos percebidos.",
     "Pessoas", "ISO 27001:2022 A.6.1", "partial", "needs_improvement", "RH", "", ""),
    ("A.6.2", "A.6.2", "Termos e condições de emprego",
     "Os contratos de trabalho devem indicar as responsabilidades do pessoal e da organização em matéria de segurança de informação.",
     "Pessoas", "ISO 27001:2022 A.6.2", "implemented", "effective", "RH / Jurídico", "", ""),
    ("A.6.3", "A.6.3", "Consciencialização, educação e formação em segurança da informação",
     "O pessoal da organização e partes interessadas relevantes devem receber sensibilização, educação e formação em segurança de informação adequadas, com atualizações regulares da política e procedimentos relevantes para a sua função.",
     "Pessoas", "ISO 27001:2022 A.6.3 · NIS2 Art.21(2)(g)", "partial", "needs_improvement", "ISO / RH", "", ""),
    ("A.6.4", "A.6.4", "Processo disciplinar",
     "Um processo disciplinar formal deve ser estabelecido e comunicado para tomar ações contra pessoal e outras partes interessadas que tenham cometido uma violação da política de segurança.",
     "Pessoas", "ISO 27001:2022 A.6.4", "partial", "needs_improvement", "RH / Jurídico", "", ""),
    ("A.6.5", "A.6.5", "Responsabilidades após cessação ou mudança de funções",
     "Responsabilidades e deveres de segurança de informação que permanecem válidos após a cessação ou mudança de funções devem ser definidos, aplicados e comunicados.",
     "Pessoas", "ISO 27001:2022 A.6.5", "implemented", "effective", "RH", "", ""),
    ("A.6.6", "A.6.6", "Acordos de confidencialidade ou não-divulgação (NDA)",
     "Acordos de confidencialidade ou não-divulgação que reflitam as necessidades de proteção de informação da organização devem ser identificados, documentados, revistos regularmente e assinados pelo pessoal e partes interessadas.",
     "Pessoas", "ISO 27001:2022 A.6.6", "implemented", "effective", "RH / Jurídico", "", ""),
    ("A.6.7", "A.6.7", "Trabalho remoto",
     "Medidas de segurança devem ser implementadas quando o pessoal trabalha remotamente para proteger a informação acedida, processada ou armazenada fora das instalações da organização.",
     "Pessoas", "ISO 27001:2022 A.6.7", "partial", "needs_improvement", "DTI - Segurança / RH", "", ""),
    ("A.6.8", "A.6.8", "Reporte de eventos de segurança da informação",
     "A organização deve disponibilizar um mecanismo para que o pessoal reporte eventos de segurança observados ou suspeitos através de canais apropriados em tempo útil.",
     "Pessoas", "ISO 27001:2022 A.6.8", "partial", "needs_improvement", "ISO", "", ""),

    # ─── 7. Physical controls ────────────────────────────────────────────────
    ("A.7.1", "A.7.1", "Perímetros de segurança física",
     "Perímetros de segurança devem ser definidos e usados para proteger áreas que contêm informação e outros ativos associados.",
     "Físico", "ISO 27001:2022 A.7.1", "implemented", "effective", "Facilities / Segurança Física", "", ""),
    ("A.7.2", "A.7.2", "Entradas físicas",
     "Áreas seguras devem ser protegidas por controlos de entrada e pontos de acesso apropriados.",
     "Físico", "ISO 27001:2022 A.7.2", "implemented", "effective", "Facilities", "", ""),
    ("A.7.3", "A.7.3", "Proteção de escritórios, salas e instalações",
     "A segurança física para escritórios, salas e instalações deve ser projetada e implementada.",
     "Físico", "ISO 27001:2022 A.7.3", "implemented", "effective", "Facilities", "", ""),
    ("A.7.4", "A.7.4", "Monitorização de segurança física",
     "As instalações devem ser continuamente monitorizadas contra acessos físicos não autorizados.",
     "Físico", "ISO 27001:2022 A.7.4", "implemented", "effective", "Segurança Física", "", ""),
    ("A.7.5", "A.7.5", "Proteção contra ameaças físicas e ambientais",
     "Proteção contra ameaças físicas e ambientais, como desastres naturais e outras ameaças intencionais ou não intencionais à infraestrutura, deve ser projetada e implementada.",
     "Físico", "ISO 27001:2022 A.7.5", "partial", "needs_improvement", "Facilities", "", ""),
    ("A.7.6", "A.7.6", "Trabalho em áreas seguras",
     "Medidas de segurança para trabalho em áreas seguras devem ser projetadas e implementadas.",
     "Físico", "ISO 27001:2022 A.7.6", "partial", "needs_improvement", "Facilities", "", ""),
    ("A.7.7", "A.7.7", "Secretária limpa e ecrã limpo",
     "Regras de secretária limpa para papéis e suportes de armazenamento removíveis e regras de ecrã limpo para instalações de processamento de informação devem ser definidas e adequadamente aplicadas.",
     "Físico", "ISO 27001:2022 A.7.7", "partial", "needs_improvement", "ISO", "", ""),
    ("A.7.8", "A.7.8", "Localização e proteção de equipamentos",
     "Os equipamentos devem ser localizados de forma segura e protegidos.",
     "Físico", "ISO 27001:2022 A.7.8", "implemented", "effective", "DTI - Infra", "", ""),
    ("A.7.9", "A.7.9", "Segurança de ativos fora das instalações",
     "Ativos fora das instalações devem ser protegidos.",
     "Físico", "ISO 27001:2022 A.7.9", "partial", "needs_improvement", "DTI", "", ""),
    ("A.7.10", "A.7.10", "Suportes de armazenamento",
     "Os suportes de armazenamento devem ser geridos ao longo do seu ciclo de vida de aquisição, uso, transporte e eliminação, de acordo com o esquema de classificação e requisitos de manuseamento.",
     "Físico", "ISO 27001:2022 A.7.10", "partial", "needs_improvement", "DTI", "", ""),
    ("A.7.11", "A.7.11", "Serviços de suporte (utilities)",
     "Instalações de processamento de informação devem ser protegidas contra falhas de energia e outras disrupções causadas por falhas em serviços de suporte.",
     "Físico", "ISO 27001:2022 A.7.11", "implemented", "effective", "Facilities", "", ""),
    ("A.7.12", "A.7.12", "Segurança de cablagem",
     "Os cabos que transportam energia, dados ou informação de serviços de suporte devem ser protegidos contra interceção, interferência ou danos.",
     "Físico", "ISO 27001:2022 A.7.12", "implemented", "effective", "DTI - Infra", "", ""),
    ("A.7.13", "A.7.13", "Manutenção de equipamentos",
     "Os equipamentos devem ser corretamente mantidos para garantir disponibilidade, integridade e confidencialidade da informação.",
     "Físico", "ISO 27001:2022 A.7.13", "implemented", "effective", "DTI - Infra", "", ""),
    ("A.7.14", "A.7.14", "Eliminação segura ou reutilização de equipamentos",
     "Itens de equipamento que contenham suportes de armazenamento devem ser verificados para garantir que dados sensíveis e software licenciado foram removidos ou substituídos de forma segura antes da eliminação ou reutilização.",
     "Físico", "ISO 27001:2022 A.7.14", "partial", "needs_improvement", "DTI - Infra", "", ""),

    # ─── 8. Technological controls ───────────────────────────────────────────
    ("A.8.1", "A.8.1", "Dispositivos de endpoint do utilizador",
     "Informação armazenada, processada ou acessível através de dispositivos de endpoint do utilizador deve ser protegida.",
     "Tecnológico", "ISO 27001:2022 A.8.1", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.2", "A.8.2", "Direitos de acesso privilegiado",
     "A alocação e uso de direitos de acesso privilegiado devem ser restritos e geridos.",
     "Tecnológico", "ISO 27001:2022 A.8.2", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.3", "A.8.3", "Restrição de acesso a informação",
     "O acesso a informação e outros ativos associados deve ser restringido de acordo com a política de controlo de acessos estabelecida.",
     "Tecnológico", "ISO 27001:2022 A.8.3", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.8.4", "A.8.4", "Acesso a código-fonte",
     "O acesso de leitura e escrita ao código-fonte, ferramentas de desenvolvimento e bibliotecas de software deve ser apropriadamente gerido.",
     "Tecnológico", "ISO 27001:2022 A.8.4", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.5", "A.8.5", "Autenticação segura",
     "Tecnologias e procedimentos de autenticação segura devem ser implementados com base nas restrições de acesso a informação e na política específica de controlo de acessos.",
     "Tecnológico", "ISO 27001:2022 A.8.5 · NIS2 Art.21(2)(j)", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.6", "A.8.6", "Gestão de capacidade",
     "O uso de recursos deve ser monitorizado e ajustado em linha com requisitos de capacidade atuais e expectáveis.",
     "Tecnológico", "ISO 27001:2022 A.8.6", "partial", "needs_improvement", "DTI - Infra", "", ""),
    ("A.8.7", "A.8.7", "Proteção contra malware",
     "Proteção contra malware deve ser implementada e suportada por sensibilização adequada dos utilizadores.",
     "Tecnológico", "ISO 27001:2022 A.8.7", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.8.8", "A.8.8", "Gestão de vulnerabilidades técnicas",
     "Informação sobre vulnerabilidades técnicas dos sistemas em uso deve ser obtida, a exposição da organização deve ser avaliada e medidas apropriadas devem ser tomadas.",
     "Tecnológico", "ISO 27001:2022 A.8.8 · NIS2 Art.21(2)(e)", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.9", "A.8.9", "Gestão de configurações",
     "Configurações, incluindo configurações de segurança, de hardware, software, serviços e redes, devem ser estabelecidas, documentadas, implementadas, monitorizadas e revistas.",
     "Tecnológico", "ISO 27001:2022 A.8.9", "partial", "needs_improvement", "DTI - Infra", "", ""),
    ("A.8.10", "A.8.10", "Eliminação de informação",
     "Informação armazenada em sistemas, dispositivos ou em qualquer outro suporte deve ser eliminada quando deixar de ser necessária.",
     "Tecnológico", "ISO 27001:2022 A.8.10", "partial", "needs_improvement", "DTI", "", ""),
    ("A.8.11", "A.8.11", "Mascaramento de dados (data masking)",
     "Mascaramento de dados deve ser usado de acordo com a política específica de controlo de acessos e outras políticas, e requisitos de negócio, tomando em consideração a legislação aplicável.",
     "Tecnológico", "ISO 27001:2022 A.8.11", "not_implemented", "untested", "DTI - Dev", "", ""),
    ("A.8.12", "A.8.12", "Prevenção de fuga de dados (DLP)",
     "Medidas de prevenção de fuga de dados devem ser aplicadas a sistemas, redes e outros dispositivos que processem, armazenem ou transmitam informação sensível.",
     "Tecnológico", "ISO 27001:2022 A.8.12", "not_implemented", "untested", "DTI - Segurança", "", ""),
    ("A.8.13", "A.8.13", "Cópias de segurança de informação",
     "Cópias de segurança de informação, software e sistemas devem ser mantidas e regularmente testadas de acordo com a política específica sobre backup.",
     "Tecnológico", "ISO 27001:2022 A.8.13 · NIS2 Art.21(2)(c)", "implemented", "effective", "DTI - Infra", "", ""),
    ("A.8.14", "A.8.14", "Redundância de instalações de processamento de informação",
     "Instalações de processamento de informação devem ser implementadas com redundância suficiente para satisfazer requisitos de disponibilidade.",
     "Tecnológico", "ISO 27001:2022 A.8.14", "partial", "needs_improvement", "DTI - Infra", "", ""),
    ("A.8.15", "A.8.15", "Registo (logging)",
     "Logs que registem atividades, exceções, falhas e outros eventos relevantes devem ser produzidos, armazenados, protegidos e analisados.",
     "Tecnológico", "ISO 27001:2022 A.8.15", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.16", "A.8.16", "Atividades de monitorização",
     "Redes, sistemas e aplicações devem ser monitorizados para deteção de comportamento anómalo e tomada de ações apropriadas para avaliar potenciais incidentes.",
     "Tecnológico", "ISO 27001:2022 A.8.16", "partial", "needs_improvement", "DTI - Segurança / SOC", "", ""),
    ("A.8.17", "A.8.17", "Sincronização de relógios",
     "Os relógios dos sistemas de processamento de informação usados pela organização devem ser sincronizados com fontes de tempo aprovadas.",
     "Tecnológico", "ISO 27001:2022 A.8.17", "implemented", "effective", "DTI - Infra", "", ""),
    ("A.8.18", "A.8.18", "Uso de programas utilitários privilegiados",
     "O uso de programas utilitários capazes de sobrepor controlos de sistema e aplicações deve ser restrito e rigorosamente controlado.",
     "Tecnológico", "ISO 27001:2022 A.8.18", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.19", "A.8.19", "Instalação de software em sistemas operacionais",
     "Procedimentos e medidas devem ser implementados para gerir de forma segura a instalação de software em sistemas operacionais.",
     "Tecnológico", "ISO 27001:2022 A.8.19", "partial", "needs_improvement", "DTI - Infra", "", ""),
    ("A.8.20", "A.8.20", "Segurança de redes",
     "Redes e dispositivos de rede devem ser protegidos, geridos e controlados para proteger a informação em sistemas e aplicações.",
     "Tecnológico", "ISO 27001:2022 A.8.20", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.8.21", "A.8.21", "Segurança de serviços de rede",
     "Mecanismos de segurança, níveis de serviço e requisitos de serviço de serviços de rede devem ser identificados, implementados e monitorizados.",
     "Tecnológico", "ISO 27001:2022 A.8.21", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.22", "A.8.22", "Segregação de redes",
     "Grupos de serviços de informação, utilizadores e sistemas de informação devem ser segregados nas redes da organização.",
     "Tecnológico", "ISO 27001:2022 A.8.22", "partial", "needs_improvement", "DTI - Infra", "", ""),
    ("A.8.23", "A.8.23", "Filtragem web",
     "O acesso a websites externos deve ser gerido para reduzir a exposição a conteúdo malicioso.",
     "Tecnológico", "ISO 27001:2022 A.8.23", "implemented", "effective", "DTI - Segurança", "", ""),
    ("A.8.24", "A.8.24", "Uso de criptografia",
     "Regras para o uso efetivo de criptografia, incluindo gestão de chaves criptográficas, devem ser definidas e implementadas.",
     "Tecnológico", "ISO 27001:2022 A.8.24 · NIS2 Art.21(2)(h)", "partial", "needs_improvement", "DTI - Segurança", "", ""),
    ("A.8.25", "A.8.25", "Ciclo de vida de desenvolvimento seguro",
     "Regras para o desenvolvimento seguro de software e sistemas devem ser estabelecidas e aplicadas.",
     "Tecnológico", "ISO 27001:2022 A.8.25", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.26", "A.8.26", "Requisitos de segurança de aplicações",
     "Requisitos de segurança de informação devem ser identificados, especificados e aprovados aquando do desenvolvimento ou aquisição de aplicações.",
     "Tecnológico", "ISO 27001:2022 A.8.26", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.27", "A.8.27", "Princípios de arquitetura e engenharia de sistemas seguros",
     "Princípios para engenharia de sistemas seguros devem ser estabelecidos, documentados, mantidos e aplicados a qualquer atividade de desenvolvimento de sistemas.",
     "Tecnológico", "ISO 27001:2022 A.8.27", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.28", "A.8.28", "Codificação segura",
     "Princípios de codificação segura devem ser aplicados ao desenvolvimento de software.",
     "Tecnológico", "ISO 27001:2022 A.8.28", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.29", "A.8.29", "Testes de segurança em desenvolvimento e aceitação",
     "Processos de testes de segurança devem ser definidos e implementados no ciclo de vida de desenvolvimento.",
     "Tecnológico", "ISO 27001:2022 A.8.29", "partial", "needs_improvement", "DTI - Dev / QA", "", ""),
    ("A.8.30", "A.8.30", "Desenvolvimento subcontratado (outsourcing)",
     "A organização deve direcionar, monitorizar e rever as atividades relacionadas com desenvolvimento subcontratado.",
     "Tecnológico", "ISO 27001:2022 A.8.30", "partial", "needs_improvement", "DTI - Dev / Compras", "", ""),
    ("A.8.31", "A.8.31", "Separação de ambientes de desenvolvimento, teste e produção",
     "Ambientes de desenvolvimento, teste e produção devem ser separados e protegidos.",
     "Tecnológico", "ISO 27001:2022 A.8.31", "implemented", "effective", "DTI - Dev", "", ""),
    ("A.8.32", "A.8.32", "Gestão de mudanças",
     "Mudanças em instalações de processamento de informação e em sistemas de informação devem ser sujeitas a procedimentos de gestão de mudança.",
     "Tecnológico", "ISO 27001:2022 A.8.32", "partial", "needs_improvement", "DTI", "", ""),
    ("A.8.33", "A.8.33", "Informação de teste",
     "A informação de teste deve ser apropriadamente selecionada, protegida e gerida.",
     "Tecnológico", "ISO 27001:2022 A.8.33", "partial", "needs_improvement", "DTI - Dev", "", ""),
    ("A.8.34", "A.8.34", "Proteção de sistemas durante testes de auditoria",
     "Testes de auditoria e outras atividades de garantia que envolvam avaliação de sistemas operacionais devem ser planeados e acordados entre o auditor e a direção apropriada.",
     "Tecnológico", "ISO 27001:2022 A.8.34", "partial", "needs_improvement", "Auditoria / DTI", "", ""),
]


def seed():
    conn = sqlite3.connect(DB)
    cur  = conn.cursor()

    added = 0
    skipped = 0
    for (cid, code, name, desc, cat, fw_refs, status, eff, owner, risk_ids, notes) in ISO_CONTROLS:
        # Check if exists
        cur.execute("SELECT 1 FROM controls WHERE id = ?", (cid,))
        if cur.fetchone():
            skipped += 1
            continue
        cur.execute("""
            INSERT INTO controls (id, code, name, description, category, framework_refs, status, effectiveness, owner, risk_ids, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """, (cid, code, name, desc, cat, fw_refs, status, eff, owner, risk_ids, notes))
        added += 1

    conn.commit()
    print(f"ISO 27001: {added} controlos novos inseridos, {skipped} já existiam.")

    # Resumo final
    cur.execute("SELECT COUNT(*) FROM controls WHERE id LIKE 'A.%'")
    total = cur.fetchone()[0]
    print(f"Total ISO 27001 (A.*): {total} controlos")

    cur.execute("SELECT category, COUNT(*) FROM controls WHERE id LIKE 'A.%' GROUP BY category")
    print("Por categoria:")
    for r in cur.fetchall():
        print(f"  {r[0]}: {r[1]}")

    conn.close()


if __name__ == "__main__":
    seed()
